version: '2'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"

  web:
    build: .
    image: codeforamerica/crisisresponse
    command: ./bin/serve
    environment:
      DB_HOST: db
      DB_USER: postgres
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/app
