version: '2'
services:
  backup:
    image: postgres:latest
    command: |
      bash -c 'exec pg_dump -h db -p 5432 -U postgres -v -d crisisresponse_development > /backups/`date '+%Y-%m-%d_%H:%M:%S'`.sql'
    links:
      - db
    volumes:
      - './backups:/backups'

  cache:
    image: memcached:latest

  db:
    image: postgres:latest
    ports:
      - "5432:5432"

  elk:
    image: willdurand/elk
    ports:
      - 81:80
    volumes_from:
      - web

  logspout:
    image: bekt/logspout-logstash
    restart: on-failure
    environment:
      ROUTE_URIS: logstash://logstash:5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  restore:
    build: containers/restore
    entrypoint: |
      psql -h db -p 5432 -U postgres -v -d crisisresponse_development -f
    links:
      - db
    volumes:
      - '.:/backup'

  web:
    build: .
    image: codeforamerica/crisisresponse
    command: ./bin/serve
    env_file:
      - .env
      - .env.local
    ports:
      - "3000:3000"
    links:
      - db
      - cache
    volumes:
      - .:/app
